# Generated by Django 6.0.3 on 2026-04-07 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReminderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reminder_interval_hours", models.PositiveIntegerField(default=4)),
            ],
            options={
                "verbose_name": "Reminder Configuration",
                "verbose_name_plural": "Reminder Configuration",
            },
        ),
        migrations.CreateModel(
            name="Roommate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BottleFillEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of bottles filled"
                    ),
                ),
                ("filled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "roommate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fills",
                        to="water.roommate",
                    ),
                ),
            ],
        ),
    ]
